### ISSUE TITLE
为什么说 SparseArray 这种方式不太好呢？

### ISSUE THREAD

**Issue by android-xiaowei** [GcsSloop/diycode#3]
你好：
     魔法师，有个疑问想问下你。

去年参加DevFest听到秋百万的讲解，他比较不赞成的就是采用SparseArray这种的；
并且我看到drakeet的项目中也有这个说法，为什么SparseArray这种方式不太好呢，我看你的项目中用到了。
https://github.com/drakeet/MultiType/pull/8

**Comment by GcsSloop** [comment]
我去看了秋百万的那个PPT，和 drakeet 的 Issues。
百万大神说的是性能问题，使用 SparseArray 性能会降低。
drakeet 则主要是认为使用id作为索引不直观，不方便。
drakeet 所说的方便不方便主要是个人习惯或者喜好，就不论述了，每个人都可以能持有不同的观点。

主要说明一下百万大神所说的性能问题。

在网上有一些说使用 SparseArray 代替 HashMap 存储 View 的说法，这个主要是因为 HashMap 占用空间过大，而 SparseArray 占用空间则要小很多，由于 Android 设备内存要比电脑小很多，所以这上非常重要。
实际上 SparseArray 的读写性能要比通常的 HashMap 低，这和其存储结构有关。

SparseArray 为了查找更快速，使用了二分查找法，因此其内部存储结构必须是有序的，所以每插入一个数据都可能导致后续数据的移动，因此它数据插入性能还是相当低下的。但读取性能要好很多。

关于 SparseArray 的性能应该是这样的：

> 传统 ViewHolder > SparseArray > findViewById

所以使用 SparseArray 实际上是损耗了一部分性能的。

但是，具体到编码过程中就要考虑很多问题了，时间、空间以及编码复杂度。

由于这里我使用的布局并不算特别复杂，所以插入数据的次数并不会太多，所以存储 View 的性能损耗还可以接受。

最后就是编码复杂度的问题了，由于使用 SparseArray 创建 ViewHolder 可以通用，在所有可复用的条目上都可以使用，否则就需要为每一种条目都单独创建 ViewHolder，代码量会增加很多。

具体情况具体分析吧，如果是特别复杂的布局，对性能要求比较高的话，还是推荐使用传统的 ViewHolder。

**Comment by android-xiaowei** [comment]
我今天把diycode的代码clone下来看了一遍，确实这个项目中所有的不管activity还是什么用到的都是ViewHolder，这个感觉很新颖，很特别😁，还有就是项目中的布局并不复杂的，您解释了一下，确实每个人都有不同的观点，都有每个人的方式。

最后谢谢您的解答。
